version: '3'
services:
  redis-cache:
    container_name: redis-cache
    build: redis
    restart: unless-stopped
    command: redis-server --requirepass root
    ports:
      - 6379:6379
    networks:
      - kite-dev-network

networks:
  kite-dev-network:
    external: true
