version: '3'

tasks:
  default:
    cmds:
      - task --list

  docker-prod:
    desc: Runs the docker compose command for the prod environment (up, down, build)
    cmds:
      - if [ {{.CLI_ARGS}} = build ]; then docker compose -f frontend/docker/docker-compose.yml -p kite-prod {{.CLI_ARGS}} --no-cache; fi
      - if [ {{.CLI_ARGS}} = up ]; then docker compose -f frontend/docker/docker-compose.yml -p kite-prod {{.CLI_ARGS}} --build -d; fi
      - if [ {{.CLI_ARGS}} = down ]; then docker compose -f frontend/docker/docker-compose.yml -p kite-prod {{.CLI_ARGS}}; fi

  docker-dev:
    desc: Runs the docker compose command for the dev environment (up, down)
    cmds:
      - if [ {{.CLI_ARGS}} = build ]; then docker compose -f frontend/docker/docker-compose.dev.yml -p kite-dev {{.CLI_ARGS}} --no-cache; fi
      - if [ {{.CLI_ARGS}} = up ]; then docker compose -f frontend/docker/docker-compose.dev.yml -p kite-dev {{.CLI_ARGS}} --build -d; fi
      - if [ {{.CLI_ARGS}} = down ]; then docker compose -f frontend/docker/docker-compose.dev.yml -p kite-dev {{.CLI_ARGS}}; fi

  run:
    desc: Runs the script with the provided name (clean, update, install)
    cmds:
      - sudo bash scripts/{{.CLI_ARGS}}.sh
