#!/usr/bin/env ansible-playbook

- hosts: all
  become: true

  roles:
    - role: system
      tags:
        - system

    - role: docker
      tags:
        - docker

    - role: fail2ban
      when: enable_fail2ban | default(False)
      tags:
        - fail2ban

    - role: ufw
      when: enable_ufw | default(False)
      tags:
        - ufw

    - role: ssh
      tags:
        - ssh
