################################################################
# Global configuration
################################################################

global:
  checkNewVersion: true
  sendAnonymousUsage: false

################################################################
# EntryPoints configuration
################################################################

entryPoints:
  web:
    address: :80

################################################################
# Traefik logs configuration
################################################################

log:
  level: ERROR
  format: common
  filePath: /var/log/traefik/traefik.log

################################################################
# Access logs configuration
################################################################

accesslog:
  format: common
  filePath: /var/log/traefik/access.log

################################################################
# Docker configuration backend
################################################################

providers:
  docker:
    exposedByDefault: false
  file:
    directory: /etc/traefik
    watch: true
