- name: Install fail2ban
  package:
    name: fail2ban
    state: present

- name: Install the jail.local file
  template:
    src: "jail.local.j2"
    dest: "/etc/fail2ban/jail.local"
    mode: 0644
    owner: root
    group: root
  notify:
    - Restart fail2ban

- name: Make sure the fail2ban systemd service is enabled and started
  service:
    name: fail2ban
    state: started
    enabled: yes
