- name: Check if there's authorized_keys
  stat:
    path: /home/{{ username }}/.ssh/authorized_keys
  register: authorized_keys
  changed_when: (not authorized_keys.stat.exists) or (authorized_keys.stat.size == 0)

- name: Install cryptography
  pip:
    name: cryptography
    version: 38.0.4

- name: Create the SSH directory
  file:
    path: "/home/{{ username }}/.ssh"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0700

- name: Install the existing public key
  when: ssh_public_key is defined
  authorized_key:
    user: "{{ username }}"
    key: "{{ ssh_public_key }}"

- name: Update SSH configuration to be more secure
  register: ssh_config
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    validate: "sshd -T -f %s"
    mode: 0644
  with_items:
    - regexp: "^#?PasswordAuthentication"
      line: "PasswordAuthentication no"
    - regexp: "^#?AddressFamily"
      line: "AddressFamily inet"
    - regexp: "^#?PermitRootLogin"
      line: "PermitRootLogin no"
    - regexp: "^#?Port"
      line: "Port {{ ssh_port }}"
    - regexp: "^#?PermitEmptyPasswords"
      line: "PermitEmptyPasswords no"
    - regexp: "^#?X11Forwarding"
      line: "X11Forwarding no"

- name: Notify user about changes
  when: (ssh_config.changed or authorized_keys.changed)
  import_tasks: notify_user.yml
