name: Frontend Deployment

on:
  push:
    tags:
      - '*'
    paths:
      - "frontend/**"

  workflow_dispatch:

jobs:
  deploy-cache:
    name: deploy redis docker image
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up QEMU for Docker
        uses: docker/setup-qemu-action@v2

      - name: Set up Buildx for Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push cache
        uses: docker/build-push-action@v3
        with:
          context: frontend/docker/redis
          file: frontend/docker/redis/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cache:latest

  docker-deploy:
    name: deploy svelte, nginx docker images
    timeout-minutes: 15
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    environment: production
    env:
      PUBLIC_CONTACT_EMAIL: ${{ vars.PUBLIC_CONTACT_EMAIL }}
      PUBLIC_SITE_URL: ${{ vars.PUBLIC_SITE_URL }}
      PUBLIC_CMS_ENDPOINT: ${{ vars.PUBLIC_CMS_ENDPOINT }}
      PUBLIC_ASSET_ENDPOINT: ${{ vars.PUBLIC_ASSET_ENDPOINT }}
      REDIS_URL: ${{ secrets.REDIS_URL }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install dependencies
        run: yarn turbo init

      - name: Build the turbo repo
        run: yarn turbo build

      - name: Set up QEMU for Docker
        uses: docker/setup-qemu-action@v2

      - name: Set up Buildx for Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: frontend/app/build
          file: frontend/app/build/docker/nginx/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/proxy:latest

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: frontend/app/build
          file: frontend/app/build/docker/sveltekit/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/webserver:latest
