- name: "Set overcommit_memory in sysctl for redis"
  ansible.posix.sysctl:
    name: vm.overcommit_memory
    value: '1'
    state: present

- name: Create the traefik directory
  file:
    path: "/etc/traefik"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Copy traefik.yaml file
  template:
    src: "traefik.yml.j2"
    dest: "/etc/traefik/traefik.yml"

- name: Deploy docker compopse stack
  docker_compose:
    project_name: kite
    remove_orphans: true
    definition:
      version: "3"
      services:
        watchtower:
          image: "containrrr/watchtower:1.5.3"
          restart: unless-stopped
          command: --schedule "* */15 * * * *"
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock

        traefik-router:
          image: "traefik:v2.10"
          restart: unless-stopped
          ports:
            - "80:80"
            - "443:443"
          volumes:
            - /etc/traefik:/etc/traefik
            - traefik-ssl-certs:/ssl-certs
            - /var/run/docker.sock:/var/run/docker.sock:ro
          networks:
            - internal-network

        directus-cms:
          image: directus/directus:9.23
          restart: unless-stopped
          volumes:
            - cms-uploads:/directus/uploads
            - cms-database:/directus/database
          networks:
            - internal-network
          depends_on:
            - traefik-router
          environment:
            "KEY": "{{ cms_key }}"
            "SECRET": "{{ cms_secret }}"
            "DB_CLIENT": "sqlite3"
            "DB_FILENAME": "database/database.sql"
            "CORS_ENABLED": "true"
            "RATE_LIMITER_ENABLED": "true"
            "CACHE_ENABLED": "true"
            "ADMIN_EMAIL": "{{ cms_admin_email }}"
            "ADMIN_PASSWORD": "{{ cms_admin_password }}"
            "PUBLIC_URL": "https://admin.{{ root_host }}"
            "FLOWS_EXEC_ALLOWED_MODULES": "axios"
          labels:
            traefik.enable: true
            traefik.http.routers.directus.entrypoints: web, websecure
            traefik.http.routers.directus.rule: Host(`admin.{{ root_host }}`)
            traefik.http.routers.directus.tls: true
            traefik.http.routers.directus.tls.certresolver: zerossl

        redis-cache:
          container_name: redis-cache
          image: kitashoersel/cache:latest
          restart: unless-stopped
          command: redis-server --requirepass {{ redis_password }}
          networks:
            - internal-network

        webserver:
          image: kitashoersel/webserver:latest
          restart: unless-stopped
          environment:
            "PUBLIC_CONTACT_EMAIL": "{{ contact_email }}"
            "PUBLIC_SITE_URL": "{{ site_url }}"
            "PUBLIC_CMS_ENDPOINT": "{{ cms_endpoint }}"
            "PUBLIC_ASSET_ENDPOINT": "{{ asset_endpoint }}"
            "REDIS_URL": "{{ redis_urL }}"
          networks:
            - internal-network

        proxy:
          image: kitashoersel/proxy:latest
          restart: unless-stopped
          networks:
            - internal-network
          depends_on:
            - traefik-router
          labels:
            traefik.enable: true
            traefik.http.routers.nginx.entrypoints: web, websecure
            traefik.http.routers.nginx.rule: Host(`{{ root_host }}`)
            traefik.http.routers.nginx.tls: true
            traefik.http.routers.nginx.tls.certresolver: zerossl
            traefik.http.routers.nginx-router.service: nginx-service
            traefik.http.services.nginx-service.loadbalancer.server.port: 3001

      volumes:
        traefik-ssl-certs:
          driver: local
        cms-uploads:
          driver: local
        cms-database:
          driver: local

      networks:
        internal-network:
          driver: bridge
